name: Build APK
on:
  workflow_dispatch:

env:
  CORE_SLN: 
  UNITY_PROJECT:
  BUILD_TARGET: 
  BUILD_NAME

jobs:
  Build-Backend:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Backend
        run: msbuild ${{ env.CORE_SLN }}/${{ env.CORE_SLN }}.sln /p:Configuration="Release"

      - name: After Build Backend
        run: msbuild ${{ env.CORE_SLN }}/${{ env.CORE_SLN }}.sln /t:AfterBuild /p:Configuration="Release"

      - name: Check Backend Dlls
        run: dir ${{ github.workspace }}\${{ env.UNITY_PROJECT }}\Assets\Plugins

      - name: Publish Backend Dlls
        uses: actions/upload-artifact@v2
        with:
          name: backend-dlls
          path: ${{ github.workspace }}\${{ env.UNITY_PROJECT }}\Assets\Plugins

  Build-APK:
    needs: Build-Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Backend Dlls
        uses: actions/download-artifact@v2
        with:
          name: backend-dlls
          path: ${{ github.workspace }}/${{ env.UNITY_PROJECT }}/Assets/Plugins

      - name: Create Library Folder
        run: mkdir -p ${{ github.workspace }}/${{ env.UNITY_PROJECT }}/Library

      - name: Cache Library Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/${{ env.UNITY_PROJECT }}/Library
          key: Library-${{ env.UNITY_PROJECT }}-${{ env.BUILD_TARGET }}
          restore-keys: |
            Library-${{ env.UNITY_PROJECT }}-
            Library-

      - name: Build APK
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ env.BUILD_TARGET }}
          projectPath: ${{ github.workspace }}/${{ env.UNITY_PROJECT }}
          buildsPath: build
          buildName: ${{ env.BUILD_NAME }}
          
      - name: Publish APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}.apk
          path: ${{ github.workspace }}/build/${{ env.BUILD_TARGET }}/${{ env.BUILD_NAME }}.apk