name: Pull Request
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:
        
env:
  CORE_SLN: 
  UNITY_PROJECT: 

jobs:
  Build-Backend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Backend
        run: msbuild ${{ env.CORE_SLN }}/${{ env.CORE_SLN }}.sln /p:Configuration="Release"

      - name: After Build Backend
        run: msbuild ${{ env.CORE_SLN }}/${{ env.CORE_SLN }}.sln /t:AfterBuild /p:Configuration="Release"

      - name: Check Backend Dlls
        run: dir ${{ github.workspace }}\${{ env.UNITY_PROJECT }}\Assets\Plugins